# Generated by Django 3.0.6 on 2020-05-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0003_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='type',
            new_name='role',
        ),
    ]
