# Generated by Django 3.0.6 on 2020-05-23 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0007_auto_20200523_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leads',
            old_name='role',
            new_name='status',
        ),
    ]
