# Generated by Django 3.0.6 on 2020-05-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0008_auto_20200523_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('account_fixing', 'Account fixing'), ('not_interested', 'Not interested'), ('deposit', 'Deposit'), ('registered', 'Registered'), ('waiting', 'Waiting'), ('sales_work', 'Sales work')], default='new', max_length=25),
        ),
    ]
