# Generated by Django 3.0.6 on 2020-05-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0010_leads_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
