# Generated by Django 3.0.6 on 2020-05-23 13:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0011_auto_20200523_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='closer',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='manager',
        ),
        migrations.AddField(
            model_name='leads',
            name='manager',
            field=models.ManyToManyField(blank=True, related_name='lead_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
