# Generated by Django 3.0.6 on 2020-05-23 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0012_auto_20200523_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='closer',
            field=models.ManyToManyField(blank=True, related_name='lead_closer', to=settings.AUTH_USER_MODEL),
        ),
    ]
