# Generated by Django 3.0.6 on 2020-05-23 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0013_leads_closer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='closer',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='manager',
        ),
        migrations.AddField(
            model_name='leads',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
