# Generated by Django 3.0.6 on 2020-05-24 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0015_auto_20200524_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leads',
            options={'get_latest_by': ['id']},
        ),
    ]
