# Generated by Django 3.0.6 on 2020-05-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0016_auto_20200524_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('account fixing', 'Account fixing'), ('not interested', 'Not interested'), ('deposit', 'Deposit'), ('registered', 'Registered'), ('waiting', 'Waiting'), ('sales work', 'Sales work')], default='new', max_length=25),
        ),
    ]
