# Generated by Django 3.0.6 on 2020-05-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0017_auto_20200525_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='update',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
