# Generated by Django 3.0.6 on 2020-05-25 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0020_auto_20200525_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planning_manager', to='acount.Leads'),
        ),
    ]
