# Generated by Django 3.0.6 on 2020-05-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0021_planning_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
