# Generated by Django 3.0.6 on 2020-05-25 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0022_planning_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='creator',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='planning',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planning',
            name='type',
            field=models.CharField(choices=[('First call', 'First call'), ('Callback', 'Callback'), ('Platform show', 'Platform show'), ('Account fixing', 'Account fixing'), ('Trial deal', 'Trial deal'), ('Deposit', 'Deposit')], default='First call', max_length=50),
        ),
        migrations.AlterField(
            model_name='planning',
            name='update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
