# Generated by Django 3.0.6 on 2020-05-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0023_auto_20200526_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='notification',
            field=models.BooleanField(default=True),
        ),
    ]
